arrowParens = "avoid"
bracketSpacing = true
insertPragma = false
jsxBracketSameLine = false
printWidth = 80
proseWrap = "always"
quoteProps = "consistent"
requirePragma = false
semi = true
singleQuote = true
tabWidth = 2
trailingComma = "all"

[[overrides]]
files = ["*.ts", "*.js", "*.tsx", ".jsx", "*.mjs", "*.json", "*.json5"]
[overrides.options]
printWidth = 120

[[overrides]]
files = "*.md"
[overrides.options]
proseWrap = "never"
